# Generated by Django 2.0.6 on 2018-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default='0000000'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='0000000'),
        ),
    ]
