# Generated by Django 2.0.6 on 2018-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180702_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='0000000', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='0000000', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='0000000', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='0000000', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_data',
            field=models.CharField(default='0000000', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='0000000', max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default='0000000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imglink',
            field=models.CharField(default='0000000', max_length=800),
        ),
    ]
